---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.backend.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: {{ .Values.backend.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.backend.db.user }}
  DB_PASSWORD: {{ .Values.backend.db.password }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.backend.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.backend.db.host }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: {{ .Values.backend.db.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.backend.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
