---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_USER: devenes
  MYSQL_DATABASE: phonebook
  MYSQL_DATABASE_HOST: mysql-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
        - name: resultserver
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysqlSecretName }}
                  key: mysql_admin_password
          envFrom:
            - configMapRef:
                name: {{ .Values.mysqlConfigMap }}
---
apiVersion: v1
kind: Service
metadata:
  name: resultserver-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: resultserver-deploy
spec:
  type: NodePort
  selector:
    app: resultserver-deploy
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.nodePort }}

