---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.frontend.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.frontend.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.frontend.backendHost }}
            - name: DB_USER
              value: dbuser
            - name: DB_PASSWORD
              value: dbpassword
            - name: DB_NAME
              value: phonebook
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.frontend.namespace }}
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}

