---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
        - name: webserver
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysqlSecretName }}
                  key: mysql_admin_password
          envFrom:
            - configMapRef:
                name: {{ .Values.mysqlConfigMap }}


---
apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: webserver-deploy
spec:
  type: NodePort
  selector:
    app: webserver-deploy
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.nodePort }}
